#!/bin/sh

# Assure that the kernel has module support.
[ -e /proc/ksyms -o -e /proc/modules ] || exit 0

case "${1}" in
    start)

        echo "Loading SPI modules"
	/sbin/modprobe spi-bcm2835aux >/dev/null
	/sbin/modprobe spi-bcm2835 >/dev/null
	/sbin/modprobe spi-gpio >/dev/null
	/sbin/modprobe spi-bitbang >/dev/null
	/sbin/modprobe spidev >/dev/null
	# Allow access for everyone
	chmod a+rw /dev/spidev0.0
	chmod a+rw /dev/spidev0.1
	;;

    *)
        echo "Usage: ${0} {start}"
        exit 1
        ;;
esac
