#!/bin/sh

case "${1}" in
    start)

        echo "Starting Pure Data"
	/usr/bin/pd -nogui -noadc -lib /usr/local/lib/pd-externals/disis_spi /boot/patch.pd &
	;;

    *)
        echo "Usage: ${0} {start}"
        exit 1
        ;;
esac
